nameapp/urls.py
from django.contrib import admin
from django.urls import path, include # 추가
from nameapp import views

app_name= 'nameapp'
urlpatterns = [
    path('', views.main, name='main'),
    path('book/', views.addressesbook, name='addressesbook'),
    path('book-search/', views.get_contacts, name='get_contacts'),
    path('notfound/', views.notfound, name='notfound'),
    path('predict/', views.predict_kospi, name='predict_kospi'),
    path('api/predict/', views.KospiPredictAPIView.as_view(), name="predict_kospi_api"),
    path('api/predict-serialize/', views.KospiPredictSerializeAPIView.as_view()),
    path('chart', views.ChartView.as_view(), name="chart"),
    path('chart1', views.ChartView1.as_view(), name="chart1"),
]

# urlpatterns = patterns('',
#     url(r'^docs/', include('rest_framework_swagger.urls')),
#     url(r'^$','addressesapp.views.main'),
#     url(r'^book/','addressesapp.views.addressesbook',name='addressesbook'),
#     url(r'^delete/(?P<name>.*)/','addressesapp.views.delete_person', name='delete_person'),
#     url(r'^book-search/','addressesapp.views.get_contacts', name='get_contacts'),
#     url(r'^addresses-list/', AddressesList.as_view(), name='addresses-list'),
#     url(r'^notfound/','addressesapp.views.notfound',name='notfound'),
#     url(r'^admin/', include(admin.site.urls)),
# )

test_server/urls.py
from django.contrib import admin
from django.urls import path, include # 추가

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nameapp/', include('nameapp.urls')), # 추가
]

nameapp/models.py
from django.db import models

# Create your models here.

# 종목 테이블
class StockTable(models.Model):
    code = models.CharField("종목코드", max_length=10, unique=True, null=False)
    name = models.CharField("종목명", max_length=20, null=False)
    sector = models.CharField("산업구분(KRX)", max_length=100, null=True)
    industry = models.CharField("주요제품(KRX)", max_length=100, null=True)
    #categories = models.CharField("섹터명(NAVER)", max_length=10, null=True)
    division = models.CharField("구분", max_length=10, null=False)

    def __str__(self):
        return '%s %s' % (self.code, self.name) 
        # admin의 record name 표시 변경, (list_display는 좁은 범위 변경)

class Kospi(models.Model):
    date = models.DateField("날짜", max_length=10, null=False)
    code = models.CharField("코드", max_length=10, null=False)
    open = models.FloatField("시가", null=True)
    high = models.FloatField("고가", null=True)
    low = models.FloatField("저가", null=True)
    close = models.FloatField("종가", null=True)
    volume = models.FloatField("거래량", null=True)
    total = models.FloatField("시가총액", null=True)
    shares = models.FloatField("주식수", null=True)

    def __str__(self):
        return self.code

    class Meta:
        ordering = ('code',)
        unique_together = (('date', 'code'),)  # 쌍으로 unique 설정, 중복불가
        # db_table = 'stock_kospi' # db의 table name을 변경한다.
        verbose_name = '코스피'  # admin의 table name을 변경한다.
        verbose_name_plural = '코스피 기초정보 테이블'


class Kosdaq(models.Model):
    date = models.DateField("날짜", max_length=10, null=False)
    code = models.CharField("코드", max_length=10, null=False)
    open = models.FloatField("시가", null=True)
    high = models.FloatField("고가", null=True)
    low = models.FloatField("저가", null=True)
    close = models.FloatField("종가", null=True)
    volume = models.FloatField("거래량", null=True)
    total = models.FloatField("시가총액", null=True)
    shares = models.FloatField("주식수", null=True)

    def __str__(self):
        return self.code

    class Meta:
        ordering = ('code',)
        unique_together = (('date', 'code'),)  # 쌍으로 unique 설정, 중복불가
        # db_table = 'stock_kodaq' # db의 table name을 변경한다.
        verbose_name = '코스닥'  # admin의 table name을 변경한다.
        verbose_name_plural = '코스닥 기초정보 테이블'


# 재무정보
class CompanyStat(models.Model):
    date = models.CharField('날짜', max_length=10, null=False)
    code = models.CharField('종목코드', max_length=10, null=False)
    freq = models.CharField('주기', max_length=5, null=False)
    gubun = models.CharField('구분', max_length=5, null=False)
    sale =  models.FloatField('매출액', null=True)
    profit =  models.FloatField('영업이익', null=True)
    netincome =  models.FloatField('당기순이익', null=True)
    d_netincome =  models.FloatField('지배순이익', null=True)
    b_netincome =  models.FloatField('비지배순이익', null=True)
    asset =  models.FloatField('자산총계', null=True)
    liability =  models.FloatField('부채총계', null=True)
    equity =  models.FloatField('자본총계', null=True)
    d_equity =  models.FloatField('지배순지분', null=True)
    b_equity =  models.FloatField('비지배지분', null=True)
    equity_stock =  models.FloatField('자본금', null=True)

    class Meta:
        # unique_together를 하면 내부적으로 아래와 같은 구문이 실행된다.
        # CREATE UNIQUE INDEX `nameapp_companyextr_date_code_uniq` ON `nameapp_companyextr` (`date`,`code`);
        unique_together = (('date', 'code', 'freq', 'gubun'),) # 쌍으로 unique 설정, 중복불가
        #db_table = 'Company_D_Year' # db의 table name을 변경한다.
        verbose_name = '재무정보' # admin의 table name을 변경한다.
        verbose_name_plural = '재무정보 테이블'

    # def __str__(self):
    #     return '%s : %s' % (self.code, self.date) # admin의 record name 표시 변경
    
# 재무비율정보
class CompanyExtr(models.Model):
    date = models.CharField('날짜', max_length=10, null=False)
    code = models.CharField('종목코드', max_length=10, null=False)
    freq = models.CharField('주기', max_length=5, null=False)
    d_eps =  models.FloatField('연결EPS', null=True)
    b_eps =  models.FloatField('개별EPS', null=True)
    per =  models.FloatField('PER', null=True)
    bps =  models.FloatField('BPS', null=True)
    pbr =  models.FloatField('PBR', null=True)
    dps =  models.FloatField('DPS', null=True)
    dps_rate =  models.FloatField('배당수익률', null=True)
    roe =  models.FloatField('ROE', null=True)
    netincome_rate =  models.FloatField('순이익률', null=True)
    profit_rate =  models.FloatField('영업이익률', null=True)
    price =  models.FloatField('주가', null=True)

    class Meta:
        unique_together = (('date', 'code', 'freq'),) # 쌍으로 unique 설정, 중복불가
        verbose_name = '재무비율' # admin의 table name을 변경한다.
        verbose_name_plural = '재무비율 테이블'


class KospiPredict(models.Model):
    date = models.DateField("날짜", max_length=10, null=False, unique=True)
    close = models.FloatField("종가", null=True)
    open = models.FloatField("시가", null=True)
    real_return = models.FloatField("실제값", null=True)
    pred_return = models.FloatField("예측값", null=True)
    signal = models.IntegerField("매매신호", null=True)
    buy = models.IntegerField("매수시점", null=True)
    sell = models.IntegerField("매도시점", null=True)

    def __str__(self):
        return '날짜:%s, 매매신호:%s' % (self.date, self.signal) 

    class Meta:
        verbose_name = '코스피 예측'  # admin의 table name을 변경한다.
        verbose_name_plural = '코스피 예측정보 테이블'

nameapp/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from nameapp.models import CompanyStat, CompanyExtr, KospiPredict
from nameapp.serializers import KospiPredictSerializer
from django.shortcuts import redirect

from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import generics
from rest_framework import mixins
from django.views.generic import View
from django_pandas.io import read_frame

import urllib
from ast import literal_eval
from time import mktime, strptime
from nameapp.backtesting import backtest_run
import pandas as pd

# Create your views here.

def main(request):
    context = {}
    print('main view')  
    return render(request, 'nameapp/home.html', context) 


def addressesbook(request):
    context = {}
    print('addressbook view')
    get_data = request.GET
    code = get_data.get('code', None)
    if CompanyStat.objects.filter(code='A'+code).exists():
        fndata_dy = CompanyStat.objects.filter(code='A'+code, gubun='연결', freq='연간').order_by('-date')
        fndata_dq = CompanyStat.objects.filter(code='A'+code, gubun='연결', freq='분기').order_by('-date')
    else:
        return render(request, 'nameapp/nopersonfound.html', context)
    context['fndata_dy'] = fndata_dy
    context['fndata_dq'] = fndata_dq
    context['code'] = code
    return render(request, 'nameapp/book.html', context)


def get_contacts(request):
    context = {}
    print('get contacts view')
    if request.method == 'GET':
        get_data = request.GET
        data = get_data.get('term','')
        print('get contacts:', data)
        if data == '':
            return render(request, 'nameapp/home.html', context)
        else:
            return redirect('%s?%s' % (reverse('nameapp:addressesbook'),
                                urllib.parse.urlencode({'code': data})))


def notfound(request):
    context = {}
    print('notfound view')    
    return render(request, 'nameapp/nopersonfound.html', context)


def predict_kospi(request):
    context = {}
    context['predict'] = KospiPredict.objects.all().order_by('-date')
    return render(request, 'nameapp/predict_list.html', context)


# 데이터를 JSON 형태로 반환, 결과를 rest framework api view로 보여준다.
# Query Set의 메소드, values, values_list 등 알아보기 
# https://hyunalee.tistory.com/42
# https://lqez.github.io/blog/django-queryset-basic.html
class KospiPredictAPIView(APIView):

    authentication_classes = []
    permission_classes = []

    def get(self, request):
        stocks = KospiPredict.objects.all().order_by('date')

        close_list = []
        real_list = []
        pred_list = []
        signal_list = []
        open_list = []
        label_list = []
        for stock in stocks:
            time_tuple = strptime(str(stock.date), '%Y-%m-%d')  
            utc_now = mktime(time_tuple) * 1000           
            close_list.append([utc_now, stock.close])
            real_list.append([utc_now, stock.real_return])
            pred_list.append([utc_now, stock.pred_return])
            signal_list.append([utc_now, stock.signal])
            open_list.append([utc_now, stock.open])

        buy_records = KospiPredict.objects.filter(buy=1)
        sell_records = KospiPredict.objects.filter(sell=1)
        for buy_record in buy_records:
            time_tuple = strptime(str(buy_record.date), '%Y-%m-%d')  
            utc_now = mktime(time_tuple) * 1000
            label_list.append({'x': utc_now, 'title': 'B', 'text': 'BUY'})
        for sell_record in sell_records:
            time_tuple = strptime(str(sell_record.date), '%Y-%m-%d')  
            utc_now = mktime(time_tuple) * 1000
            label_list.append({'x': utc_now, 'title': 'S', 'text': 'SELL'})              
          
        data = {
            'close': close_list,
            'signal': signal_list,
            'pred': pred_list,
            'open': open_list,
            'label': label_list,
        }

        return Response(data)


class KospiPredictSerializeAPIView(APIView): 

    authentication_classes = []
    permission_classes = []

    def get(self, request):
        stocks = KospiPredict.objects.all().order_by('-date')
        serializer = KospiPredictSerializer(stocks, read_only=True, many=True)
        return Response(serializer.data)


# class KospiPredictListAPI(generics.GenericAPIView, mixins.ListModelMixin):    
#     serializer_class = KospiPredictSerializer
#     def get_queryset(self):
#         return KospiPredict.objects.all().order_by('-date')
#     def get(self, request, *args, **kwargs):
#         return self.list(request, *args, **kwargs)


class ChartView(View):
    def get(self, request, *args, **kwargs):
        backtest_algo1()
        return render(request, 'nameapp/chart.html')


class ChartView1(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'nameapp/chart_copy.html')


def backtest_algo1():

    base_kospi = KospiPredict.objects.all() # DB에 있는 내용으로 백테스팅한다.
    df_result_db = read_frame(base_kospi, fieldnames=['date', 'close', 'open', 'buy', 'sell'])
    #df_result_db['date'] = df_result_db['date'].astype(np.str) # 주의
    df_result_db.set_index('date',inplace=True)
    df_result_db.fillna(0, inplace=True)

    거래결과1, 계좌평가결과1 = backtest_run(df_local=df_result_db, 투자금=10000000, 투자금고정= True, 기간=120)
    수익거래 = 거래결과1[거래결과1['수익률']>0]['수익률']
    손실거래 = 거래결과1[거래결과1['수익률']<0]['수익률']

    # 3개월,6개월,1년 / 거래횟수, win/loss ratio, max win, max loss, sharp ratio, MDD, 수익률sum, mean, std
    print('딥러닝모델전략 성과')
    print('거래횟수:',len(거래결과1), '/', len(계좌평가결과1) )
    print('win:', len(수익거래) )
    print('loss:', len(손실거래) )
    print('win/loss ratio:', len(수익거래) / len(손실거래))
    print('max win:', 수익거래.max() )
    print('max loss:', 손실거래.min() )
    print('수익률합:', round(거래결과1['수익률'].sum(),2), '%')

    과거가격 = 계좌평가결과1.iloc[0]['현재가']
    현재가격 = 계좌평가결과1.iloc[-1]['현재가']
    print('기준수익률:', round(( 현재가격 - 과거가격 ) / 과거가격 * 100 - 0.03,2), '%')


def backtest_algo2():
    # 평균회귀 전략    
    print('평균회귀전략 성과')


    return True

def backtest_algo3():
    # 변동성돌파 전략    
    print('변동성돌파전략 성과')


    return True

templates/nameapp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Test page for Stock Search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block stylesheets %}
        <!-- Bootstrap provided CSS files. -->
        <link href="/static/css/bootstrap.css" rel="stylesheet">
        <style type="text/css">
          body {
            padding-top: 60px;
            padding-bottom: 40px;
          }
        </style>
        <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
    {% endblock stylesheets %}

    {% block javascript %}

        <!-- Bootstrap related javascript files -->
     
        <script src="/static/js/jquery.js"></script>
        <script src="/static/js/bootstrap-transition.js"></script>
        <script src="/static/js/bootstrap-alert.js"></script>
        <script src="/static/js/bootstrap-modal.js"></script>
        <script src="/static/js/bootstrap-dropdown.js"></script>
        <script src="/static/js/bootstrap-scrollspy.js"></script>
        <script src="/static/js/bootstrap-tab.js"></script>
        <script src="/static/js/bootstrap-tooltip.js"></script>
        <script src="/static/js/bootstrap-popover.js"></script>
        <script src="/static/js/bootstrap-button.js"></script>
        <script src="/static/js/bootstrap-collapse.js"></script>
        <script src="/static/js/bootstrap-carousel.js"></script>
        <script src="/static/js/bootstrap-typeahead.js"></script>
    {% endblock javascript %}
  </head>

  <body>
    {% block header %}
        <div class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
              <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </a>
              <div class="nav-collapse">
                <ul class="nav">
                  <li class="active"><a href="/nameapp/">Home</a></li>
                </ul>
              </div>
                <form class="navbar-search pull-left" action="{% url 'nameapp:get_contacts' %}" method="GET">
                  {% csrf_token %}
                   <div style="overflow: hidden; padding-right: .5em;">
                     <input type="text" name="term" style="width: 70%;" />
                     <input type="submit" name="search" value="Find" size="30" style="float: right" />
                    </div>
                </form>
             </div>
            </div>
          </div>
        </div>
    {% endblock header %}

    <div class="container">
        <div class="hero-unit">
            {% block content %}
            {% endblock content %}

            {% block footer %}
                <section id="lines"><hr></section>
                <section id="footer">
                     Provided by AI
                </section>
            {% endblock footer %}
        </div>
    </div> 

  </body>
</html>

templates/nameapp/book.html
{% extends "nameapp/base.html" %}

{% block content %}
<h2 align = Center>Company Financial Statment</h2>
<br>
<br>
<section id="gridSystem">
<p align = Center><strong> 종목코드:{{ code }}</strong></p>
<p align = Center><strong> 연결연간 </strong></p>
{% for item in fndata_dy %}
<div class="row show-grid">
<p align = Center>{{ item.date }} 매출액:{{ item.sale }} 
    영업이익:{{ item.profit }} 순이익:{{ item.netincome }}</p>
</div>
{% endfor %}
<p align = Center><strong> 연결분기 </strong></p>
{% for item in fndata_dq %}
<div class="row show-grid">
<p align = Center>{{ item.date }} 매출액:{{ item.sale }} 
    영업이익:{{ item.profit }} 순이익:{{ item.netincome }}</p>
</div>
{% endfor %}
</section>

{% endblock content %}

templates/nameapp/chart.html
{% extends "nameapp/base.html" %}

{% block content %}

<div id="container">
  <!--
  <script src="https://code.highcharts.com/stock/highstock.js"></script>
  <script src="https://code.highcharts.com/stock/modules/data.js"></script>
  <script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
  <script src="https://code.highcharts.com/stock/modules/export-data.js"></script>
  -->
  <script src="https://code.highcharts.com/stock/highstock.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>

    function setChart() {
      Highcharts.setOption({
        global: {
          useUTC: false
        }
      });
    };

    $.ajax({
      url: "{% url 'nameapp:predict_kospi_api' %}",
      dataType: 'json',
      success: function (data) {

        Highcharts.setOptions({
          global: {
            useUTC: false
          }
        });

        Highcharts.stockChart("container", {

          chart: {
            height: 500
          },

          title: { 
            text: '모의매매 백테스팅' 
          }, 

          rangeSelector: {
            selected: 5,
            inputEnabled: false
          },

          xAxis: {
            type: 'datetime',
            labels:{
              formatter: function(){
                return Highcharts.dateFormat('%y.%m.%d', this.value);
              },
              step: 3
            }
          },

          yAxis: [{
            labels: {
              format: '{value}',
              style: {
                color: 'rgba(0,0,0,.6)',
              },
            },
            opposite: true,
            tickInterval: 0.5,
          }, {
            labels: {
              format: '{value}p',
              style: {
                color: 'rgba(0,0,0,.6)',
              },
              x: 30,
            },
            opposite: false,
            tickInterval: 50,   
          }],

          tooltip: {
            xDateFormat: '%Y-%m-%d',
            split: true
          },

          series: [          
          {
              name: '종가',          
              data: data.close,
              yAxis: 1,
              lineWidth: 3,
              id: 'close',
          },

          {
            type: 'flags',
            data: data.label,
            yAxis: 1,
            onSeries: 'close',
            shape: 'squarepin',
            width: 16
        }],

          legend: {
            enabled: true, 
            align: 'left',
            verticalAlign: 'top',
            floating: true,
            x: 30,
            y: 70
          },

          responsive: {
            rules: [{
              condition: {
                maxWidth: 600
              },
              chartOptions: {
                chart: {
                  height: 300
                },
                navigator: {
                  enabled: false
                }
              }
            }, {
              condition: {
                maxWidth: 600
              },
              chartOptions: {
                chart: {
                  height: 300
                },
                navigator: {
                  enabled: false
                }
              }
            }]
          }
        });
      }
    });

  </script>
</div>




<br><br>




<div id="container2">
  <!--
  <script src="https://code.highcharts.com/stock/highstock.js"></script>
  <script src="https://code.highcharts.com/stock/modules/data.js"></script>
  <script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
  <script src="https://code.highcharts.com/stock/modules/export-data.js"></script>
  -->
  <script src="https://code.highcharts.com/stock/highstock.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>

    function setChart() {
      Highcharts.setOption({
        global: {
          useUTC: false
        }
      });
    };

    $.ajax({
      url: "{% url 'nameapp:predict_kospi_api' %}",
      dataType: 'json',
      success: function (data) {

        Highcharts.setOptions({
          global: {
            useUTC: false
          }
        });

        Highcharts.stockChart("container2", {

          chart: {
            height: 500
          },

          title: { 
            text: '코스피지수 예측지표' 
          }, 

          rangeSelector: {
            selected: 5,
            inputEnabled: false
          },

          xAxis: {
            type: 'datetime',
            labels:{
              formatter: function(){
                return Highcharts.dateFormat('%y.%m.%d', this.value);
              },
              step: 3
            }
          },

          yAxis: [{
            labels: {
              format: '{value}',
              style: {
                color: 'rgba(0,0,0,.6)',
              },
            },
            opposite: true,
            tickInterval: 0.5,
          }, {
            labels: {
              format: '{value}p',
              style: {
                color: 'rgba(0,0,0,.6)',
              },
              x: 30,
            },
            opposite: false,
            tickInterval: 50,   
          }],

          tooltip: {
            xDateFormat: '%Y-%m-%d',
            split: true
          },

          series: [{
              name: '단기변동예측',          
              data: data.pred,
              color: 'rgba(0,200,0,.6)',
              lineWidth: 2
          }, 

          {
              name: '신호',          
              data: data.signal,
              color: 'rgba(255,0,0,.6)',
              lineWidth: 2
          },  
          
          {
              name: '종가',          
              data: data.close,
              yAxis: 1,
              lineWidth: 3,
              marker: {
                enabled: true,
                radius: 3
              }
          }],

          legend: {
            enabled: true, 
            align: 'left',
            verticalAlign: 'top',
            floating: true,
            x: 30,
            y: 70
          },

          responsive: {
            rules: [{
              condition: {
                maxWidth: 600
              },
              chartOptions: {
                chart: {
                  height: 300
                },
                navigator: {
                  enabled: false
                }
              }
            }, {
              condition: {
                maxWidth: 600
              },
              chartOptions: {
                chart: {
                  height: 300
                },
                navigator: {
                  enabled: false
                }
              }
            }]
          }
        });
      }
    });

  </script>
</div>




















{% endblock content %}


<!--
<div id="container" data-url="{% url 'chart_data' %}"></div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $.ajax({
    url: $("#container").attr("data-url"),
    dataType: 'json',
    success: function (data) {
      Highcharts.chart("container", data);
    }
  });
</script>
-->

templates/nameapp/chart_copy.html
{% extends "nameapp/base.html" %}

{% block content %}

<div id="container">
 
  <script src="https://code.highcharts.com/stock/highstock.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>

    function setChart() {
      Highcharts.setOption({
        global: {
          useUTC: false
        }
      });
    };

    $.ajax({
      url: "{% url 'nameapp:predict_kospi_api' %}",
      dataType: 'json',
      success: function (data) {

        Highcharts.setOptions({
          global: {
            useUTC: false
          }
        });

        Highcharts.stockChart("container", {

          chart: {
            height: 500
          },

          title: { 
            text: '코스피 지수' 
          }, 

          rangeSelector: {
            selected: 5,
            inputEnabled: false
          },

          xAxis: {
            type: 'datetime',
            labels:{
              formatter: function(){
                return Highcharts.dateFormat('%y.%m.%d', this.value);
              },
              step: 3
            }
          },

          yAxis: {
            labels: {
              format: '{value}p',
              style: {
                color: 'rgba(0,0,0,.6)',
              },
              x: 30,
            },
            opposite: false,
            tickInterval: 50,   
          },

          tooltip: {
            xDateFormat: '%Y-%m-%d',
            split: true
          },

          series: [{
              name: '시가',          
              data: data.open,
              color: 'rgba(0,200,0,.6)',
              lineWidth: 2
          }, 
          {
              name: '종가',          
              data: data.close,
              lineWidth: 3
          }],

          legend: {
            enabled: true, 
            align: 'left',
            verticalAlign: 'top',
            floating: true,
            x: 30,
            y: 70
          },

          responsive: {
            rules: [{
              condition: {
                maxWidth: 600
              },
              chartOptions: {
                chart: {
                  height: 300
                },
                navigator: {
                  enabled: false
                }
              }
            }]
          }
        });
      }
    });

  </script>
</div>


{% endblock content %}


<!--
<div id="container" data-url="{% url 'chart_data' %}"></div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $.ajax({
    url: $("#container").attr("data-url"),
    dataType: 'json',
    success: function (data) {
      Highcharts.chart("container", data);
    }
  });
</script>
-->

templates/nameapp/home.html
{% extends "nameapp/base.html" %}

{% block content %}
<h2 align = Center> 재무정보 DB 확인을 위한 테스트 페이지입니다. </h2>
{% endblock content %}

templates/nameapp/nopersonfound.html
{% extends "nameapp/base.html" %}

{% block content %}
<section id="gridSystem">
<p align = Center> No Stock is found. </p>
</section>
{% endblock content %}

templates/nameapp/predict_list.html
{% extends "nameapp/base.html" %}

{% block content %}

<h2 align = Center>KOSPI PREDICT TABLE</h2>
<br>
<section id="gridSystem">
{% for pred in predict %}
<div class="row show-grid">
<p align = Center>날짜:{{ pred.date}} 종가:{{ pred.close }} 신호:{{ pred.signal }} 예측값:{{ pred.pred_return }}</p>
</div>
{% endfor %}
</section>

{% endblock content %}